# Workflow to run build.sh every day at 12:00 AM

name: "Build everyday"
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the build
        run: | 
          cd src
          ./build.sh


